---
- name: Install shift CA
  copy:
    src: etc/ssl/certs/shift-ca.pem
    dest: /usr/local/share/ca-certificates/shift-ca.crt
    owner: root
    group: root
    mode: 0644
- name: Update image ca
  shell:
    cmd: /usr/sbin/update-ca-certificates
